[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings= [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
  "forge-std/=lib/forge-std/src/",
  "openzeppelin-contracts/=lib/openzeppelin-contracts/",
  "openzeppelin/=lib/openzeppelin-contracts/contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
[rpc_endpoints]
mainnet="https://eth.public-rpc.com"
bsc="https://bscrpc.com"
pls="https://rpc.pulsechain.com"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }
bsc = { key = "${BSC_ETHERSCAN_API_KEY}", url = "https://api.bscscan.com/api" }